name: Docker Publish go app
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./go-app  # This is the directory where the Dockerfile is located
          file: ./go-app/Dockerfile  # Full path to the Dockerfile inside the go-app folder
          push: true
          tags: ghcr.io/${{ github.repository }}/go-app:latest

