name: Docker Publish Go App

on:
  push:
    branches:
      - main
  # workflow_dispatch:  # Uncomment for manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Git Commit SHA
        id: sha
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .  
          file: ./go-app/Dockerfile  # Path to  Dockerfile
          push: false  # Set to 'false' if you're just building the image locally for now
          tags: ghcr.io/aqibhafeez473/nodejs-app-cicd-githubaction/go-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .  # Again, root directory of your project
          file: ./go-app/Dockerfile
          push: true  # Push the image to GHCR
          tags: ghcr.io/aqibhafeez473/nodejs-app-cicd-githubaction/go-app:latest
