name: Docker Publish go app

on:
  push:
    branches:
      - main
  # workflow_dispatch:  # Ye manual trigger ke liye hai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./goapp/Dockerfile
          push: true
          tags: ghcr.io/aqibhafeez473/nodejs-app-cicd-githubaction/go-app:latest

